framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    validation: { enable_annotations: true }

    form: ~
    csrf_protection: true
    templating:
        engines: ['twig']

    assets:
        packages:
            UnitedCMSCoreBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitedcmscore/manifest.json"
                base_path: '/bundles/unitedcmscore'
            UnitedCMSCollectionFieldBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitedcmscollectionfield/manifest.json"
                base_path: '/bundles/unitedcmscollectionfield'
            UnitedCMSStorageBundle:
                json_manifest_path: "%kernel.project_dir%/public/bundles/unitedcmsstorage/manifest.json"
                base_path: '/bundles/unitedcmsstorage'