twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@UniteCMSCore/Form/uikit_layout.html.twig'
        - '@UniteCMSCollectionField/Form/form_widgets.html.twig'
        - '@UniteCMSStorage/Form/form_widgets.html.twig'
    globals:
        unite: '@unite.cms.manager'
        site_name: '%site_name%'
        site_background: '%site_background%'
