services:

    # A Helper for common s3 storage tasks.
    unite.cms.storage.service:
        public: true
        class: UniteCMS\StorageBundle\Service\StorageService
        arguments: ['@unite.cms.field_type_manager']

    # A file upload field.
    UniteCMS\StorageBundle\Field\Types\FileFieldType:
        tags: [unite_cms.field_type]
        arguments: ['@router.default', '%kernel.secret%', '@unite.cms.storage.service', '@security.csrf.token_manager']

    # A image upload field.
    UniteCMS\StorageBundle\Field\Types\ImageFieldType:
        tags: [unite_cms.field_type]
        arguments: ['@router.default', '%kernel.secret%', '@unite.cms.storage.service', '@security.csrf.token_manager']

    # A file graphQL schema object type.
    UniteCMS\StorageBundle\SchemaType\StorageFileType:
        tags: [unite_cms.graphql.schema_type]

    # A file graphQL schema input type.
    UniteCMS\StorageBundle\SchemaType\StorageFileInputType:
        tags: [unite_cms.graphql.schema_type]

    # A command to delete unsed files from s3 buckets.
    UniteCMS\StorageBundle\Command\StorageFileDeleteUnused:
        arguments: ['@doctrine.orm.default_entity_manager', '@unite.cms.field_type_manager']
        tags:
            - { name: 'console.command', command: 'unite:storage:delete-unused' }

    # Provide PreSignFormType form as a service for S3 presigning from type
    UniteCMS\StorageBundle\Form\PreSignFormType:
        tags: [form.type]
        arguments: ['@security.untracked_token_storage']


    UniteCMS\StorageBundle\Service\StorageService: "@unite.cms.storage.service"

    _defaults:
        bind:
            $kernelSecret: '%kernel.secret%'

    # This allows controller actions to inject services in the method call instead of calling $this->get('').
    UniteCMS\StorageBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        tags: ['controller.service_arguments']
