unitecms_core_index:
    path:     /
    methods: ['GET']
    defaults: { _controller: UniteCMSCoreBundle:Index:index }

unitecms_core_authentication:
    resource: "@UniteCMSCoreBundle/Controller/AuthenticationController.php"
    type:     annotation
    prefix:   /profile

unitecms_core_logout:
    path: /profile/logout

unitecms_core_profile:
    resource: "@UniteCMSCoreBundle/Controller/ProfileController.php"
    type:     annotation
    prefix:   /profile

unitecms_core_organizations:
    resource: "@UniteCMSCoreBundle/Controller/OrganizationController.php"
    type:     annotation
    prefix:   /profile/organizations

unitecms_core_organization_user:
    resource: "@UniteCMSCoreBundle/Controller/OrganizationUserController.php"
    type:     annotation
    prefix:   /{organization}/user
    requirements:
        organization: '[a-z0-9_]+'

unitecms_core_organization_api_key:
    resource: "@UniteCMSCoreBundle/Controller/OrganizationApiKeyController.php"
    type:     annotation
    prefix:   /{organization}/apikeys
    requirements:
        organization: '[a-z0-9_]+'

unitecms_core_domains:
    resource: "@UniteCMSCoreBundle/Controller/DomainController.php"
    type:     annotation
    prefix:   /{organization}
    requirements:
        organization: '[a-z0-9_]+'

unitecms_core_domain_member:
    resource: "@UniteCMSCoreBundle/Controller/DomainMemberController.php"
    type:     annotation
    prefix:   /{organization}/{domain}/member
    requirements:
        organization: '[a-z0-9_]+'
        domain: '[a-z0-9_]+'

unitecms_core_content:
    resource: "@UniteCMSCoreBundle/Controller/ContentController.php"
    type:     annotation
    prefix:   /{organization}/{domain}/content
    requirements:
        organization: '[a-z0-9_]+'
        domain: '[a-z0-9_]+'

unitecms_core_setting:
    resource: "@UniteCMSCoreBundle/Controller/SettingController.php"
    type:     annotation
    prefix:   /{organization}/{domain}/setting
    requirements:
        organization: '[a-z0-9_]+'
        domain: '[a-z0-9_]+'


# Add a route to api that will return the default implementation (graphQL)
unitecms_core_api:
    path:     /{organization}/{domain}/api
    methods: ['POST']
    defaults: { _controller: UniteCMSCoreBundle:GraphQLApi:index }

unitecms_core_graph_api:
    path:     /{organization}/{domain}/api/graphql
    methods: ['POST']
    defaults: { _controller: UniteCMSCoreBundle:GraphQLApi:index }
