# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: services.manual.yaml }

parameters:
    unite_cms_core.debug: '%kernel.debug%'
    unite_cms_core.default_mailer_from: '%env(MAILER_FROM)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $uniteCMSDebug: '%unite_cms_core.debug%'
            $uniteCMSDomainLogger: '@monolog.logger.unite_domain'
            $defaultMailerFrom: '%unite_cms_core.default_mailer_from%'

    _instanceof:
        UniteCMS\CoreBundle\Field\FieldTypeInterface:
            tags: ['unite.field_type']

        UniteCMS\CoreBundle\GraphQL\Schema\Provider\SchemaProviderInterface:
            tags:
                - { name: 'unite.graphql.schema_provider' }

        UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface:
            tags:
                - { name: 'unite.graphql.schema_extender', position: !php/const UniteCMS\CoreBundle\GraphQL\Schema\Extender\SchemaExtenderInterface::EXTENDER_AFTER }

        UniteCMS\CoreBundle\GraphQL\Schema\Modifier\SchemaModifierInterface:
            tags: ['unite.graphql.schema_modifier']

        UniteCMS\CoreBundle\GraphQL\Resolver\FieldResolverInterface:
            tags: ['unite.graphql.field_resolver']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    UniteCMS\CoreBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    UniteCMS\CoreBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
