# Contains all core field types
services:

  # A simple text input field
  UniteCMS\CoreBundle\Field\Types\TextFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple textarea input field
  UniteCMS\CoreBundle\Field\Types\TextAreaFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple checkbox input field
  UniteCMS\CoreBundle\Field\Types\CheckboxFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple choice input field
  UniteCMS\CoreBundle\Field\Types\ChoiceFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple choices input field that allows to select multiple values
  UniteCMS\CoreBundle\Field\Types\ChoicesFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple range input field
  UniteCMS\CoreBundle\Field\Types\RangeFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A reference input field that allows to add a reference to a content item in any domain in the same organization.
  UniteCMS\CoreBundle\Field\Types\ReferenceFieldType:
    public: false
    tags: [unite_cms.field_type]
    arguments: ['@validator', '@security.authorization_checker', '@unite.cms.manager', '@doctrine.orm.entity_manager', '@unite.cms.view_type_manager', '@templating.engine.twig', '@router', '@security.csrf.token_manager']

  # A reference input field that allows to add a reference to a content item in any domain in the same organization.
  UniteCMS\CoreBundle\Field\Types\ReferenceOfFieldType:
    public: false
    tags: [unite_cms.field_type]
    arguments: ['@validator', '@security.authorization_checker', '@unite.cms.manager', '@doctrine.orm.entity_manager', '@knp_paginator', 100]

  # An integer input field that automatically handles position indexing (on INSERT, UPDATE, DELETE).
  UniteCMS\CoreBundle\Field\Types\SortIndexFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple Date field
  UniteCMS\CoreBundle\Field\Types\DateFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple DateTime field
  UniteCMS\CoreBundle\Field\Types\DateTimeFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple Email field
  UniteCMS\CoreBundle\Field\Types\EmailFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple Integer field
  UniteCMS\CoreBundle\Field\Types\IntegerFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple Number field
  UniteCMS\CoreBundle\Field\Types\NumberFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A simple Phone field
  UniteCMS\CoreBundle\Field\Types\PhoneFieldType:
    public: false
    tags: [unite_cms.field_type]

  # A Link field with open to set a target and title
  UniteCMS\CoreBundle\Field\Types\LinkFieldType:
    public: false
    tags: [unite_cms.field_type]

  # State Field Type
  UniteCMS\CoreBundle\Field\Types\StateFieldType:
    public: false
    tags: [unite_cms.field_type]
